/** @type {import('tailwindcss').Config} */
export default {
	content: ["./src/mainview/**/*.{html,js,ts,jsx,tsx}"],
	darkMode: "class",
	theme: {
		extend: {
			colors: {
				"outline-variant": "#4e4356",
				"on-primary-fixed": "#2d004f",
				"tertiary": "#ffb781",
				"on-secondary-fixed": "#002022",
				"surface-container": "#201f22",
				"tertiary-container": "#a45500",
				"surface-dim": "#131315",
				"secondary": "#dcfdff",
				"primary-fixed-dim": "#dfb7ff",
				"surface-container-lowest": "#0e0e10",
				"primary": "#dfb7ff",
				"background": "#131315",
				"secondary-fixed-dim": "#00dce6",
				"surface-container-low": "#1c1b1e",
				"primary-container": "#9d00ff",
				"surface-container-highest": "#353437",
				"on-secondary": "#00373a",
				"secondary-fixed": "#6ff6ff",
				"error": "#ffb4ab",
				"on-error-container": "#ffdad6",
				"inverse-on-surface": "#313032",
				"on-tertiary-container": "#ffe7d8",
				"tertiary-fixed": "#ffdcc4",
				"surface-bright": "#39393b",
				"on-secondary-fixed-variant": "#004f53",
				"secondary-container": "#00f1fd",
				"on-secondary-container": "#006a6f",
				"surface-tint": "#dfb7ff",
				"error-container": "#93000a",
				"on-background": "#e5e1e4",
				"inverse-primary": "#8c00e5",
				"on-primary": "#4b007e",
				"on-error": "#690005",
				"on-tertiary-fixed": "#2f1400",
				"surface-variant": "#353437",
				"primary-fixed": "#f1daff",
				"inverse-surface": "#e5e1e4",
				"on-tertiary": "#4e2500",
				"outline": "#9a8ca2",
				"surface": "#131315",
				"on-surface": "#e5e1e4",
				"on-tertiary-fixed-variant": "#703800",
				"on-primary-fixed-variant": "#6b00b0",
				"tertiary-fixed-dim": "#ffb781",
				"on-primary-container": "#f7e5ff",
				"on-surface-variant": "#d1c1d9",
				"surface-container-high": "#2a2a2c"
			},
			fontFamily: {
				"headline": ["Space Grotesk", "sans-serif"],
				"body": ["Space Grotesk", "sans-serif"],
				"label": ["Space Grotesk", "sans-serif"],
				"mono": ["JetBrains Mono", "monospace"]
			}
		},
	},
	plugins: [],
};
